[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
  
[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 1.0
    accessibility = 1.0
    best-practices = 1.0
    seo = 1.0
    pwa = 1.0

[[plugins]]
package = "netlify-build-plugin-perfbeacon"